services:
  # Load Balancer (Entry Point)
  local.cirque.zthunworks.com:
    image: nginx:1.21.5-alpine
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - ./packages/cirque-proxy/shared:/etc/nginx/shared
      - ./packages/cirque-proxy/certs:/etc/nginx/certs
      - ./packages/cirque-proxy/conf.d:/etc/nginx/conf.d
    depends_on:
      - cirque-services-web

  # Node Ports
  cirque-services-web:
    image: node:17.3.0
    volumes:
      - .:/usr/dev
    working_dir: /usr/dev
    command: npm --workspace @zthun/cirque-web run debug
